version: '3'

services:
  react-app:
    build: .
    ports:
      - "9511:3000"
    volumes:
      - .:/opereation-app-ts
      - node_modules_volume:/opereation-app-ts/node_modules
    tty: true
    env_file:
      - .env
volumes:
  node_modules_volume:
    name: react_ts_node_modules
